server {
    listen 80;
    server_name _;
    charset utf-8;
    autoindex off;

    location / {
        root /usr/share/nginx/html;
        try_files $uri =404;
        default_type text/yaml;
        add_header Cache-Control "no-store" always;
        add_header X-Content-Type-Options "nosniff" always;
    }
}

